### PR TITLE
Sg writemerge

### PR DESCRIPTION
**Pull request by scogre**
trying to commit some changes...

### CODE REVIEW

**Comment by jswhit** [comment]
Scott:  Looking through matchdiag_writenc.py, I have a couple of questions/suggestions:

1) why initialize the arrays with NaNs?

2) instead of using setncattr, you can just set the attribute directly. For example, instead of

    obdata_A.setncattr('ps','surface pressure')

you can do

    obdata_A.ps = 'surface pressure'

3) Do you need this check

    if not(math.isnan(prepindx[nob])):

and can you just use len(nobs_nc) > 0?

4) instead of writing to numpy arrays and then dumping all the data to the netcdf file at the end, can you just write to the netcdf file directly inside the loop over diag records?  Or is that slower?

5) can you use command line args to specify the input and output files instead of hardcoding file names?

I'd like to see an example output file, perhaps you can update the one on google drive.

**Comment by jswhit** [comment]
I also see you still have separate copies of obdata for the analysis and guess (obdata_A and obdata_F).  Same for oberrdata, and useddata.  Did you see may email last week about simplifying the variables to reduce redundancy?

**Comment by scogre** [comment]
hi Jeff
I have made some changes in a new version that makes output like you
suggested last week. I am fighting with Git to be able to share that
update... attaching it here. I did not run it all the way thru because my
cpu is consumed with other work.... also attached it here.

​
 testing_write2.nc
<https://drive.google.com/a/noaa.gov/file/d/0B8gOfWVubC8dQjJ6NzNrSmNOenM/view?usp=drive_web>
​

On Mon, Feb 22, 2016 at 1:00 PM, Jeff Whitaker <notifications@github.com>
wrote:

> I also see you still have separate copies of obdata for the analysis and
> guess (obdata_A and obdata_F). Same for oberrdata, and useddata. Did you
> see may email last week about simplifying the variables to reduce
> redundancy?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jswhit/py-ncepbufr/pull/3#issuecomment-187358616>.
>



-- 
Scott Gregory

**Comment by scogre** [comment]
1-I intialize with NaNs because matching finds the index of the prepbufr
match... so I intialize the shape to the same size as the prepbufr arrays
with NaNs, then find which prepbufr indices match for each diag line,
determine which column it belongs (U,V,T, P, etc)

2- I think I must have copied that blindly from another code

3- I believe I first tried the >0 and it failed, I used the 'not-NaN' and
it worked.

4- I think writing is something that is time consuming...

5- yes.... I will make command line args- as you wrote the prep2nc
originally... I hardwired it for the sake of fewer characters on the
command line.... and at the time I was not sure how to make the executable.

Scott

On Mon, Feb 22, 2016 at 12:58 PM, Jeff Whitaker <notifications@github.com>
wrote:

> Scott: Looking through matchdiag_writenc.py, I have a couple of
> questions/suggestions:
>
> 1) why initialize the arrays with NaNs?
>
> 2) instead of using setncattr, you can just set the attribute directly.
> For example, instead of
>
> obdata_A.setncattr('ps','surface pressure')
>
> you can do
>
> obdata_A.ps = 'surface pressure'
>
> 3) Do you need this check
>
> if not(math.isnan(prepindx[nob])):
>
> and can you just use len(nobs_nc) > 0?
>
> 4) instead of writing to numpy arrays and then dumping all the data to the
> netcdf file at the end, can you just write to the netcdf file directly
> inside the loop over diag records? Or is that slower?
>
> 5) can you use command line args to specify the input and output files
> instead of hardcoding file names?
>
> I'd like to see an example output file, perhaps you can update the one on
> google drive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jswhit/py-ncepbufr/pull/3#issuecomment-187357163>.
>



-- 
Scott Gregory

**Pull request closed without merging**
