### PR TITLE
add option for using external bufrlib

### PR DESCRIPTION
**Pull request by jswhit**
built from JCSDA bufrlib project.  Addresses issue #23.

### CODE REVIEW

**Comment by jswhit** [comment]
Need to add a travis test for this.  

It's not working on my mac - when I run test/test.py i get
```
[mac28:~/python/py-ncepbufr.jcsda/test] jwhitaker% python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import ncepbufr
  File "/Users/jwhitaker/Library/Python/2.7/lib/python/site-packages/ncepbufr/__init__.py", line 1, in <module>
    import _bufrlib
ImportError: dlopen(/Users/jwhitaker/Library/Python/2.7/lib/python/site-packages/_bufrlib.so, 2): __dyld section not supported in /Users/jwhitaker/lib/libbufr.dylib
```

**Comment by jswhit** [comment]
The default cmake build uses ifort if it's installed - however numpy.distutils uses gfortran by default.  Setting FC=gfortran before building bufrlib fixes it for me - the tests pass with the external bufrlib.

**Comment by markjolah** [comment]
Hmm... I just saw that note about fortran compiler versions.  In general we may not have a gfortran built bufrlib available.  Does this mean we also need to build numpy with intel compilers?

**Comment by jswhit** [comment]
You should be able to just run `setup.py build config_fc --fcompiler=intelem`, but I haven't tested this yet.

**Pull request merged**
